import { TerraErrorMapping, TransactionError } from './types'

export const ONE_TOKEN = 1000000

export const errors: TerraErrorMapping = {
  sdk: {
    2: TransactionError.PARSE_ERROR,
    3: TransactionError.INVALID_SEQUENCE,
    4: TransactionError.UNAUTHORIZED,
    5: TransactionError.INSUFFICIENT_FUNDS,
    6: TransactionError.UNKNOWN_REQUEST,
    7: TransactionError.INVALID_ADDRESS,
    8: TransactionError.INVALID_PUBKEY,
    9: TransactionError.UNKNOWN_ADDRESS,
    10: TransactionError.INVALID_COINS,
    11: TransactionError.OUT_OF_GAS,
    12: TransactionError.MEMO_TOO_LARGE,
    13: TransactionError.INSUFFICIENT_FEE,
    14: TransactionError.MAX_SIGNATURES_REACHED,
    15: TransactionError.NO_SIGNATURES,
    16: TransactionError.FAILED_TO_ENCODE_JSON,
    17: TransactionError.FAILED_TO_DECODE_JSON,
    18: TransactionError.INVALID_REQUEST,
    19: TransactionError.TX_ALREADY_IN_MEMPOOL,
    20: TransactionError.MEMPOOL_FULL,
    21: TransactionError.TX_TOO_LARGE,
    22: TransactionError.KEY_NOT_FOUND,
    23: TransactionError.INVALID_ACCOUNT_PASSWORD,
    24: TransactionError.TX_SIGNER_NOT_MATCH,
    25: TransactionError.INVALID_GAS_ADJUSTMENT,
    26: TransactionError.INVALID_HEIGHT,
    27: TransactionError.INVALID_VERSION,
    28: TransactionError.INVALID_CHAIN_ID,
    29: TransactionError.INVALID_TYPE,
    30: TransactionError.TX_TIMEOUT_HEIGHT,
    31: TransactionError.UNKNOWN_EXTENSION_OPTIONS,
    32: TransactionError.INCORRECT_ACCOUNT_SEQUENCE,
    33: TransactionError.PROTOBUF_PACKING_FAILED,
    34: TransactionError.PROTOBUG_UNPACKING_FAILED,
    35: TransactionError.INTERNAL_LOGIC_ERROR,
    36: TransactionError.CONFLICT,
    37: TransactionError.FEATURE_NOT_SUPPORTED,
    38: TransactionError.NOT_FOUND,
    39: TransactionError.INTERNAL_IO_ERROR,
    40: TransactionError.ERROR_IN_APP_TOML,
  },
}
